name: webpack-dll-config
config:
  path: src/assets/libs
  entry:
    vendors:
      - react
      - react-dom
      - mobx
      - mobx-react
      - antd
      - antd-form-builder
      - styled-components
      - lodash