name: webpack-dll-config
js:
  path: src/assets/libs/js
  entry:
    vendors:
      - react
      - react-dom
      - antd
      - antd-form-builder
      - styled-components
      - lodash
css:
  path: src/assets/libs/css
  entry: ./src/assets/styles/index.scss